######################### Network #############################
network:
  network_port: 25565
  selfgen_cert:
    cert_password: "catmoe"
    cert_alias: "catmoe"
  custom_cert:
    enabled: false
    cert_path: "./cert.jks"
    cert_password: "catmoe"


######################### Database ############################
database:
  # default support mongodb
  # demo database_url:
  # mongodb: mongodb://localhost:27017/database_name
  #
  # Note: No need to carry username and password in url
  database_url: mongodb://localhost:27017/kat-server
  database_username:
  database_password:

####################### Storage ###############################
# The resource file storage
resource:
  # You can choose those type of resource_storage
  # 1.local
  resource_storage: local

  # If you choose `local`,
  # you can set the resource file where to store.
  data_folder_path: "./data"

####################### ExecThreads ############################
exec:
  exec_threads: 16

####################### TokenPool ##############################
# This section are the settings of token pool

tokenpool:
  # You can set the token how long to live
  #
  # Unit: Millisecond
  outdated: 10000
