name: Tests for TokenPool

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  tokenpool:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '#Skip')"
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle test
        run: ./gradlew test --tests --stacktrace "com.catkatpowered.katserver.tokenpool.TestKatTokenPool"

      - name: Upload fail reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tokenpool-test-failure
          path: build/reports
