name: Tests for Database

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  mongodb:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '#Skip')"
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up MongoDB 4.4
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle test
        run: ./gradlew test --tests --stacktrace "com.catkatpowered.katserver.database.TestMongoDBDatabase"

      - name: Upload fail reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: mongodb-test-failure
          path: build/reports
