name: Tests for Config

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  config:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '#Skip')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle test
        run: ./gradlew test -i --tests --stacktrace "com.catkatpowered.katserver.config.TestKatConfig"

      - name: Upload fail reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: config-test-failure
          path: build/reports
