name: Verify Build Github Actions

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '#Skip')"
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (build)
        run: ./gradlew build -x test
